POST http://localhost:8000/
Content-Type:application/json

{
    "email":"juan.perez@email.com",
    "password":"password123"
}

### localStorage.getItem('token')
GET  http://localhost:8000/users
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImp0aSI6ImQ2N2Y3MWY0LWIxMjEtNGQ0Mi05OTQ4LTQ2NWZkYTU1NzhmYSIsImV4cCI6MTc0OTU1OTEzMn0.ldl3d8OWwqVHMEHsSk8k-xAW8iLV-EJz3e54V-U98Qg