
GET http://localhost:8000/users

###
POST http://localhost:8000/users
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOjgwMDAvUHJveWVjdG9ERU5PRmluYW56YXNQZXJzb25hbGVzIiwic3ViIjoiMSIsImp0aSI6Ijc3OGI5YzQzLTM5YzktNDUxNy1iOGZlLTU1ZDY4Y2YyNDE3MCIsImV4cCI6MTc0OTY3NzU1M30.m_hDzVKU-Ehp262tjOcPu20MFZPkVRTOdiiHtuwH0uo

{
    "nombre":"Luis",
    "apellido":"Salamanca",
    "telefono":"3209809449",
    "direccion":"Calle45",
    "email":"luis@gmail.com",
    "password":"12345"
}

###
POST http://localhost:8000/
Content-Type: application/json

{
    "email": "juan.perez@email.com",
    "password": "password123"
}

### localStorage.getItem('token')
GET  http://localhost:8000/users
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOjgwMDAvUHJveWVjdG9ERU5PRmluYW56YXNQZXJzb25hbGVzIiwic3ViIjoxLCJqdGkiOiJhNDc1ZjE5NC0wOGFmLTQwNmYtYWU5ZS00NzE4NDJkOWQ1NTkiLCJleHAiOjE3NDk1NTk0MzR9.uhYjVGjUbrKG8i3Ok6LcZr_mFqhLOnqmnEwimvSB6hI

### Obtener todas las categorías
GET http://localhost:8000/categorias
Content-Type: application/json

### Crear nueva categoría 
POST http://localhost:8000/categorias
Content-Type: application/json

{
    "nombre": "Transporte",
    "descripcion": "Gastos de movilidad: gasolina, taxi, Uber, transporte público, mantenimiento del vehículo"
}

### Actualizar categoría existente 
PUT http://localhost:8000/categorias
Content-Type: application/json

{
    "idCategoria":"4",
    "nombre": "Gastos",
    "descripcion":"Gastos de movilidad: gasolina, taxi, Uber, transporte público, mantenimiento del vehículo"
}


###
GET http://localhost:8000/cuenta
###
POST http://localhost:8000/cuenta
Content-Type: application/json

{
    "nombre":"Michel",
    "tipoCuenta":"Tarjeta Credito",
    "saldo":"600000",
    "estado":"activo",
    "idUsuario":"1"
}
###
put http://localhost:8000/cuenta
Content-Type: application/json

{
    "idCuenta":"3",
    "nombre":"MichelG",
    "tipoCuenta":"Debito",
    "saldo":"600000",
    "estado":"inactivo",
    "idUsuario":"1"
}

###
GET http://localhost:8000/tipos-transaccion